# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinates.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinates.proto\x12\x12\x63oordinate_service\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x32\x61\n\x11\x43oordinateService\x12L\n\x0eGetCoordinates\x12\x16.google.protobuf.Empty\x1a\x1e.coordinate_service.Coordinate\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinates_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDINATE._serialized_start=70
  _COORDINATE._serialized_end=104
  _COORDINATESERVICE._serialized_start=106
  _COORDINATESERVICE._serialized_end=203
# @@protoc_insertion_point(module_scope)
