# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coordinates_pb2 as coordinates__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CoordinateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoordinates = channel.unary_stream(
                '/coordinate_service.CoordinateService/GetCoordinates',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coordinates__pb2.Coordinate.FromString,
                )


class CoordinateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoordinates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoordinates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCoordinates,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coordinates__pb2.Coordinate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinate_service.CoordinateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoordinateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/coordinate_service.CoordinateService/GetCoordinates',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coordinates__pb2.Coordinate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
